[package]
name = "convlog"
version = "0.2.0"
authors = ["Equim <sayaka@ekyu.moe>"]
edition = "2024"

[dependencies]
serde_json = "1"
serde_tuple = "1"
serde_repr = "0.1"
thiserror = "2"
num_enum = "0.7"
ahash = "0.8"
serde_with = "3"
serde = { version = "1", features = ["derive"] }
